spring:
  datasource:
    url: jdbc:postgresql://ep-wispy-lab-a1j132ka-pooler.ap-southeast-1.aws.neon.tech/neondb
    username: neondb_owner
    password: npg_y2EBdq5cIfKa
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # 또는 create / create-drop (개발 상황에 따라 변경)
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # 연결 보안을 위해 SSL 사용
  datasource-properties:
    sslmode: require

logging:
  level:
    org.hibernate.SQL: debug
