spring:
  datasource:
    url: jdbc:postgresql://ep-solitary-boat-a1gavunr-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_y2EBdq5cIfKa
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # 엔티티 기반 테이블 자동 생성
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true     # 콘솔에 SQL 출력

  # 로깅 보기 편하게 (선택)
  output:
    ansi:
      enabled: always

server:
  port: 8080
