spring:
  datasource:
    url: jdbc:postgresql://ep-wispy-lab-a1j132ka-pooler.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_y2EBdq5cIfKa&sslmode=require
    username: neondb_owner
    password: npg_y2EBdq5cIfKa
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 2aed1eb5d8cab77b823ded86af7bc51d
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8090/login/oauth2/code/kakao"
            scope: profile_nickname, profile_image
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

server:
  port: 8090

  output:
    ansi:
      enabled: always
