spring:
  datasource:
    url: jdbc:postgresql://ep-solitary-boat-a1gavunr-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_AVUxk3wYDG4m
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 2aed1eb5d8cab77b823ded86af7bc51d
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "http://192.168.0.20:8080/login/oauth2/code/kakao"
            scope:
              - profile_nickname
              - profile_image
            client-name: Kakao
          naver:
            client-id: 9yLKlIuaexaXKWqGhkmO
            client-secret: 3Wwm2XJQkJ
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "http://192.168.0.20:8080/login/oauth2/code/naver"
            scope:
              - name
              - email
              - profile_image
              - age
              - birthday
              - birthyear
              - mobile
              - gender
            client-name: Naver
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

server:
  port: 8090
  address: 0.0.0.0

  output:
    ansi:
      enabled: always
